/**
 * 文件：errorCodes.js
 * 模块：server/shared
 * 作用：后端错误码枚举（与契约文档对齐，便于统一响应）
 * 依赖：无
 * @created 2026-01-07
 * @modified 2026-01-20
 */

export const ERROR_CODES = Object.freeze({
  BAD_REQUEST: "BAD_REQUEST",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  SETTINGS_NOT_FOUND: "SETTINGS_NOT_FOUND",
  PRESET_NOT_FOUND: "PRESET_NOT_FOUND",
  CHAT_THREAD_NOT_FOUND: "CHAT_THREAD_NOT_FOUND",

  DRAFT_NOT_FOUND: "DRAFT_NOT_FOUND",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  VERSION_CONFLICT: "VERSION_CONFLICT",
  DRAFT_BUSY: "DRAFT_BUSY",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  RUN_NOT_STOPPED: "RUN_NOT_STOPPED",
  DRAFT_PENDING: "DRAFT_PENDING",
  PENDING_NOT_FOUND: "PENDING_NOT_FOUND",
  PENDING_KIND_MISMATCH: "PENDING_KIND_MISMATCH",
  DRAFT_CHANGED: "DRAFT_CHANGED",

  RESET_CONFIRM_REQUIRED: "RESET_CONFIRM_REQUIRED",

  PATCH_PATH_INVALID: "PATCH_PATH_INVALID",
  PATCH_OP_INVALID: "PATCH_OP_INVALID",
  PATCH_ROOT_FORBIDDEN: "PATCH_ROOT_FORBIDDEN",
  MODE_FORBIDDEN: "MODE_FORBIDDEN",

  MODEL_OUTPUT_INVALID_JSON: "MODEL_OUTPUT_INVALID_JSON",
  MODEL_OUTPUT_KIND_NOT_ALLOWED: "MODEL_OUTPUT_KIND_NOT_ALLOWED",
  MODEL_OUTPUT_MIXED_READ: "MODEL_OUTPUT_MIXED_READ",

  READ_REQUEST_INVALID: "READ_REQUEST_INVALID",
  READ_WORLD_INFO_AFTER_LIMIT: "READ_WORLD_INFO_AFTER_LIMIT",

  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  UPSTREAM_BAD_RESPONSE: "UPSTREAM_BAD_RESPONSE",
});
